version: '3.4'
 

services:
  clientswh:
    image: ${DOCKER_REGISTRY-}clientswh
    build:
      context: .
      dockerfile: ClientSWH/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGODB_URL=mongodb://mongodb:27017/DocRecordSvh
    depends_on:
      - postgres
      - mongo

  postgres:
    container_name: postgres
    image: postgres:16.4 
    environment:
      POSTGRES_DB: "svhdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "studadmin"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
        MONGO_INITDB_DATABASE: DocRecordSvh
        MONGO_INITDB_ROOT_USERNAME: studadmin
        MONGO_INITDB_ROOT_PASSWORD: studadmin
    hostname: mongodb-server
    ports:
       -  27017:27017
    volumes:
       - ./mongodb:/data/db
      
volumes:
  pgdata: 
  mongodb: 


