version: '3.4'
 

services:
  clientswh:
    image: ${DOCKER_REGISTRY-}clientswh
    build:
      context: .
      dockerfile: ClientSWH/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__MongoConnectionString=mongodb://studadmin:studadmin@svhmongodb:27017"
    depends_on:
      - postgres
      - mongo
  postgres:
    container_name: postgres
    image: postgres:16.4 
    environment:
      POSTGRES_DB: "svhdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "studadmin"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
  mongo:
    image: mongo:latest
    container_name: svhmongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: studadmin
      MONGO_INITDB_ROOT_PASSWORD: studadmin
    ports:
      - "27017:27017"
    volumes:
      - mongosvh:/data/db

  
volumes:
  pgdata: 
  mongosvh: 


